### PR TITLE
Add flask version

### PR DESCRIPTION
**Pull request by Manishearth**
Should be easier to daemonize.

### CODE REVIEW

**Comment by ghost** [comment]
I agree with flask-ification. It's very good and easy to use :)

**Review by jdm — COMMENTED** [review]
Why is tests.json removed?

**Comment by ghost** [comment]
Yeah, it should've gone into the package's folder.

**Comment by ghost** [comment]
Squash the last two commits, and let's merge this?

**Comment by Manishearth** [comment]
done

r? @jdm

**Comment by Manishearth** [comment]
(this is deployed and working fine)

**Pull request merged**
